apiVersion: v1
kind: Pod
metadata:
  name: error-pod-nonexistent-command
spec:
  containers:
  - name: failing-container
    image: busybox
    command: ["nonexistent-command"] # 존재하지 않는 명령 실행
    args: ["--error"]
  restartPolicy: Always # 오류 발생 시 재시작 시도 (CrashLoopBackOff 유도)
