version: '3.8'
services:
  k8s-monitor:
    build: .
    container_name: k8s-pod-monitor
    ports:
      - "5000:5000"
    volumes:
      - ~/.kube:/root/.kube:ro
      - ./data:/app/data
    restart: unless-stopped
    command: ["web"]
